spring:
  application:
    name: spring-study-material
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/shafiq_test
    username: root
    password: root
  jpa:
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.generate_statistics: true
hibernate:
  dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8082

